apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      containers:
      - image: microsoft/aci-helloworld
        imagePullPolicy: Always
        name: aci-helloworld
        resources:
          requests:
            memory: 1.5G
            cpu: 1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
      dnsPolicy: ClusterFirst
      nodeName: virtual-kubelet-aci-linux
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
