apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
      spec:
        containers:
        - name: k8s-demo
        image: daz/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: nodejs-port
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 30
